/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.VideoGenGrammarAccess;

public class VideoGenParser extends AbstractContentAssistParser {
	
	@Inject
	private VideoGenGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalVideoGenParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalVideoGenParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalVideoGenParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getVideoAccess().getAlternatives(), "rule__Video__Alternatives");
					put(grammarAccess.getVideoGenAccess().getGroup(), "rule__VideoGen__Group__0");
					put(grammarAccess.getMandatoryRuleAccess().getGroup(), "rule__MandatoryRule__Group__0");
					put(grammarAccess.getOptionnalRuleAccess().getGroup(), "rule__OptionnalRule__Group__0");
					put(grammarAccess.getAlternativeRuleAccess().getGroup(), "rule__AlternativeRule__Group__0");
					put(grammarAccess.getVideoSeqAccess().getGroup(), "rule__VideoSeq__Group__0");
					put(grammarAccess.getVideoSeqAccess().getGroup_3(), "rule__VideoSeq__Group_3__0");
					put(grammarAccess.getVideoSeqAccess().getGroup_4(), "rule__VideoSeq__Group_4__0");
					put(grammarAccess.getVideoSeqAccess().getGroup_5(), "rule__VideoSeq__Group_5__0");
					put(grammarAccess.getVideoSeqMandatoryAccess().getGroup(), "rule__VideoSeqMandatory__Group__0");
					put(grammarAccess.getVideoSeqMandatoryAccess().getGroup_3(), "rule__VideoSeqMandatory__Group_3__0");
					put(grammarAccess.getVideoSeqMandatoryAccess().getGroup_4(), "rule__VideoSeqMandatory__Group_4__0");
					put(grammarAccess.getVideoGenAccess().getVideosAssignment_2(), "rule__VideoGen__VideosAssignment_2");
					put(grammarAccess.getMandatoryRuleAccess().getSeqAssignment_1(), "rule__MandatoryRule__SeqAssignment_1");
					put(grammarAccess.getOptionnalRuleAccess().getSeqAssignment_1(), "rule__OptionnalRule__SeqAssignment_1");
					put(grammarAccess.getAlternativeRuleAccess().getIdAssignment_1(), "rule__AlternativeRule__IdAssignment_1");
					put(grammarAccess.getAlternativeRuleAccess().getAlternatvesAssignment_3(), "rule__AlternativeRule__AlternatvesAssignment_3");
					put(grammarAccess.getVideoSeqAccess().getIdAssignment_1(), "rule__VideoSeq__IdAssignment_1");
					put(grammarAccess.getVideoSeqAccess().getUrlAssignment_2(), "rule__VideoSeq__UrlAssignment_2");
					put(grammarAccess.getVideoSeqAccess().getDescriptionAssignment_3_2(), "rule__VideoSeq__DescriptionAssignment_3_2");
					put(grammarAccess.getVideoSeqAccess().getProprobabilitePercentAssignment_4_2(), "rule__VideoSeq__ProprobabilitePercentAssignment_4_2");
					put(grammarAccess.getVideoSeqAccess().getDureeSecondeAssignment_5_2(), "rule__VideoSeq__DureeSecondeAssignment_5_2");
					put(grammarAccess.getVideoSeqMandatoryAccess().getIdAssignment_1(), "rule__VideoSeqMandatory__IdAssignment_1");
					put(grammarAccess.getVideoSeqMandatoryAccess().getUrlAssignment_2(), "rule__VideoSeqMandatory__UrlAssignment_2");
					put(grammarAccess.getVideoSeqMandatoryAccess().getDescriptionAssignment_3_2(), "rule__VideoSeqMandatory__DescriptionAssignment_3_2");
					put(grammarAccess.getVideoSeqMandatoryAccess().getDureeSecondeAssignment_4_2(), "rule__VideoSeqMandatory__DureeSecondeAssignment_4_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalVideoGenParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalVideoGenParser) parser;
			typedParser.entryRuleVideoGen();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public VideoGenGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VideoGenGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
